name: Deploy Docs 

on:
 schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Check Fern version
        run: fern --version
      
      - name: Upgrade Fern
        run: fern upgrade 

      - name: Deploy Docs
        run: fern generate --docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
