name: Deploy Docs 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
      

      - name: Install python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install python dependencies
        run: pip install pyyaml

      - name: Generate docs.yml
        run: python fern/generator.py 


      - name: Install Fern CLI
        run: npm install -g fern-api
      
      - name: Deploy Docs
        run: fern generate --docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}