name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy with Fern
        uses: fern-api/action-publish@v0.0.40
        with:
          token: ${{ secrets.FERN_TOKEN }}